import React from 'react';
import { useAppContext } from '../../AppContext';
import { MinimalTemplate } from './MinimalTemplate';
import { ModernTemplate } from './ModernTemplate';
import { ClassicTemplate } from './ClassicTemplate';

export const ResumePreview = () => {
  const { state } = useAppContext();

  const renderTemplate = () => {
    switch (state.settings.template) {
      case 'minimal':
        return <MinimalTemplate data={state.data} settings={state.settings} />;
      case 'classic':
        return <ClassicTemplate data={state.data} settings={state.settings} />;
      case 'modern':
      default:
        // By default use Modern (Clean Minimalism)
        return <ModernTemplate data={state.data} settings={state.settings} />;
    }
  };

  return (
    <div className="h-full overflow-y-auto p-4 md:p-8 flex justify-center items-start print:relative print:overflow-visible print:h-auto print:p-0 print:block">
      {/* 
        A4 proportion wrapper 
        A4 is 210x297mm. The ratio is ~1:1.414.
      */}
      <div className="w-full max-w-[850px] min-h-[1202px] bg-white shadow-2xl rounded-sm print:shadow-none print:max-w-none print:w-full print:h-auto print:min-h-0 print:rounded-none origin-top transition-all">
        
        {/* Screen Version */}
        <div className="print:hidden h-full">
          {renderTemplate()}
        </div>

        {/* Print Version */}
        <table className="w-full hidden print:table">
          <thead className="table-header-group">
            <tr><td className="h-[7.5mm]"></td></tr>
          </thead>
          <tbody className="table-row-group">
            <tr>
              <td className="px-[15mm]">
                {renderTemplate()}
                <div className="mt-8 pb-4 text-center text-[6px] text-gray-300/30 print:block hidden font-light tracking-wide opacity-50">
                  <p>&copy; SIMON DEJMEK / <a href="https://resume-builder.dejmsi.cz" target="_blank" rel="noopener noreferrer" className="hover:text-gray-400">resume-builder.dejmsi.cz</a> / <a href="https://github.com/dejmsi/resume-builder" target="_blank" rel="noopener noreferrer" className="hover:text-gray-400">github.com/dejmsi/resume-builder</a></p>
                  <p className="absolute w-0 h-0 overflow-hidden text-[1px] text-transparent select-none z-[-1] opacity-0 print:opacity-100 print:text-[#ffffff]">
                    App generated by https://resume-builder.dejmsi.cz
                  </p>
                </div>
              </td>
            </tr>
          </tbody>
          <tfoot className="table-footer-group">
            <tr><td className="h-[7.5mm]"></td></tr>
          </tfoot>
        </table>

      </div>
    </div>
  );
};
